[project]
name = "wstunnel"
version = "0.1.0"
description = "A websocket tunnel"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
  { name = "Your Name", email = "you@example.com" }
]
dependencies = [
  "websockets",
  "aiohttp",
  "pyyaml",
  "aiodns",
  "pysocks",
  "click",
  "cryptography",
  "h2",
  "async-timeout"
]

[project.scripts]
wstunnel = "wstunnel.app:main"
